//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_1517_PRECIADO_CE_FINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaCabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaCabecera()
        {
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
        }
    
        public int NumeroFactura { get; set; }
        public string CodCliente { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public decimal TotalFactura { get; set; }
        public decimal IGVFactura { get; set; }
        public decimal NetoFactura { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
    }
}
