//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_1517_PRECIADO_CE_FINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int IDDetalleFactura { get; set; }
        public int NumeroFactura { get; set; }
        public string CodProducto { get; set; }
        public string NombreProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioProducto { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual FacturaCabecera FacturaCabecera { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
